### ISSUE TITLE
Input validity check failing

### ISSUE THREAD

**Issue by cristobal-vildosola** [IntegratedAlarmSystem-Group/ias-webserver#15]
The webserver is not checking the validity of its input. When the value send has iasValidity "UNRELIABLE", the output sent to the display has validity "RELIABLE".
![image](https://user-images.githubusercontent.com/26608721/35992448-0cc141fc-0ce9-11e8-9f2f-07934e14c828.png)

**Comment by sfehlandt** [comment]
No longer an issue.
Probably solved by refactor. See f5c38056d06824f205ea23de58a44eae701e45d4
