### ISSUE TITLE
The parse of the messages received from the ias core fails because tStamp is not a field anymore

### ISSUE THREAD

**Issue by jmaldonadof** [IntegratedAlarmSystem-Group/ias-webserver#18]
The format of the received messages must to be reviewed to update the fields name.

**Comment by acaproni** [comment]
Who is parsing? Do you have a log?

My feeling is that you are using anew version of the core without cleaning the kafka queue. Yoou should stop kafkla, remove everything from kafkadata/* and restart kafkka. The problem should disappera.

**Comment by jmaldonadof** [comment]
When the webserver receive the messages from the core, it needs to read the json and interpret it.  After the last changes in the core, the tStamp field was removed, or the name of the field was changed, so the webserver crushed when it tried to read the json, but we know how to fix. 
That is the reason why we mention before the need of a little test to check if the format of the delivered message changes in a way that impact in how the webserver expect to receive the messages. So the test can alert that we need to fix the webserver too. (issue #51 in the ias repository)
