### ISSUE TITLE
Revert global updates logic between Webserver and Display

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias-webserver#20]
Currently, Ias Display requests every 2 seconds a global update of all Alarms to the Webserver

In order to avoid performance issues triggered by multiple clients making such requests at different times (unsynchronized) , we should make the Webserver push periodic global updates to clients and the Display should stop making these requests.

**Comment by mxolivares** [comment]
Closed with 79dee9a0
