### ISSUE TITLE
Remove CDB

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias-webserver#45]
Issues identified:
1. We have decided to use JSON files instead of a real database for the CDB.
2. We have also identified a problem, since we read every IASIO form the CDB to initialize the AlarmsCollection, we are also reading IASIOs that are output of internal ASCE and never written to kafka by the DASUs. 

Solution:
1. We should read the ias.json file directly and remove the connection to the CDB.
2. We should initializae the AlarmsCollection based on the fixtures needed for the panels-config.

**Comment by jmaldonadof** [comment]
The webserver still needs to read the iasios.json to get the alarm short description. But to define what alarms must be add to the collection the webserver reads first the panel-config.
