### ISSUE TITLE
Add tests to check consumers properly

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias-webserver#6]
Current tests did not detect bug from issue #5 .

We should either modify those tests or add a new test that asserts those cases

**Comment by sfehlandt** [comment]
This is a configuration issue. Instead of testing we added a comment in the relevant part of the code to warn developers of the issue and tell them how to configure things properly

**Comment by acaproni** [comment]
Sebastian, is the developr in charge of setting the configuraton? Or will it be the alarm system administrator?

**Comment by sfehlandt** [comment]
We are talking about different configurations. This refers to the configuration of the Django Project, channels, streams, groups, etc. So it is not an issue of development of code, but configuration of the project (which is also done through code)

**Comment by acaproni** [comment]
Fine, thank you.
